using System;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Mindora.Application.Interfaces;

namespace Mindora.Infrastructure.Services
{
    public class GeminiService : IGeminiService
    {
        private readonly HttpClient _httpClient;
        private readonly string _apiKey;
        private readonly string _model;
        private readonly string _baseUrl;
        private readonly ILogger<GeminiService> _logger;

        public GeminiService(
            HttpClient httpClient,
            IConfiguration configuration,
            ILogger<GeminiService> logger)
        {
            _httpClient = httpClient;
            _logger = logger;

            _apiKey = configuration["Gemini:ApiKey"]
                ?? throw new InvalidOperationException(
                    "Gemini API Key is missing from appsettings.json");

            _model = configuration["Gemini:Model"] ?? "gemini-1.5-flash";

            _baseUrl =
                (configuration["Gemini:BaseUrl"]
                ?? "https://generativelanguage.googleapis.com/v1beta/models")
                .TrimEnd('/');
        }

        public async Task<string> GenerateResponseAsync(
            string prompt,
            string? context = null)
        {
            if (string.IsNullOrWhiteSpace(prompt))
            {
                throw new ArgumentException(
                    "Prompt cannot be null or empty.",
                    nameof(prompt));
            }

            var fullPrompt = string.IsNullOrWhiteSpace(context)
                ? prompt
                : $"""
                   Context:
                   {context}

                   User:
                   {prompt}

                   Assistant:
                   """;

            var requestBody = new
            {
                contents = new[]
                {
                    new
                    {
                        parts = new[]
                        {
                            new
                            {
                                text = fullPrompt
                            }
                        }
                    }
                },
                generationConfig = new
                {
                    temperature = 0.7,
                    maxOutputTokens = 512,
                    topP = 0.95,
                    topK = 40
                }
            };

            var url =
                $"{_baseUrl}/{_model}:generateContent?key={_apiKey}";

            using var content = new StringContent(
                JsonSerializer.Serialize(requestBody),
                Encoding.UTF8,
                "application/json");

            _logger.LogInformation(
                "Sending request to Gemini Model: {Model}",
                _model);

            var response =
                await _httpClient.PostAsync(url, content);

            var responseJson =
                await response.Content.ReadAsStringAsync();

            if (!response.IsSuccessStatusCode)
            {
                _logger.LogError(
                    "Gemini API Error: {StatusCode}\n{Response}",
                    response.StatusCode,
                    responseJson);

                throw new Exception(
                    $"Gemini API Error ({(int)response.StatusCode}):\n{responseJson}");
            }

            try
            {
                using var document =
                    JsonDocument.Parse(responseJson);

                var root = document.RootElement;

                if (!root.TryGetProperty("candidates", out var candidates)
                    || candidates.GetArrayLength() == 0)
                {
                    return "No response generated by Gemini.";
                }

                var text =
                    candidates[0]
                    .GetProperty("content")
                    .GetProperty("parts")[0]
                    .GetProperty("text")
                    .GetString();

                return string.IsNullOrWhiteSpace(text)
                    ? "No response generated by Gemini."
                    : text;
            }
            catch (Exception ex)
            {
                _logger.LogError(
                    ex,
                    "Failed to parse Gemini response.");

                throw new Exception(
                    $"Failed to parse Gemini response.\nResponse:\n{responseJson}");
            }
        }
    }
}