using System.Globalization;
using System.Text;
using Mindora.Application.DTOs.Reporting;
using Mindora.Application.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Mindora.Infrastructure.Services
{
    public class ReportExportService : IReportExportService
    {
        private readonly IReportGeneratorService _generator;

        public ReportExportService(IReportGeneratorService generator)
        {
            _generator = generator;
            QuestPDF.Settings.License = LicenseType.Community;
        }

        public async Task<byte[]> ExportToCsvAsync(ReportFilterDto filter)
        {
            var data = await _generator.GenerateReportDataAsync(filter);

            var sb = new StringBuilder();
            sb.AppendLine(string.Join(",", data.Columns.Select(c => $"\"{c}\"")));

            foreach (var row in data.Rows)
            {
                sb.AppendLine(string.Join(",", row.Select(v => $"\"{v?.Replace("\"", "\"\"")}\"")));
            }

            return Encoding.UTF8.GetBytes(sb.ToString());
        }

        public async Task<byte[]> ExportToExcelAsync(ReportFilterDto filter)
        {
            // For now using CSV-compatible output with .xls extension as minimal support.
            // Later switch to ClosedXML or EPPlus for true XLSX.
            var csv = await ExportToCsvAsync(filter);
            return csv;
        }

        public async Task<byte[]> ExportToPdfAsync(ReportFilterDto filter)
        {
            var data = await _generator.GenerateReportDataAsync(filter);

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4.Landscape());
                    page.Margin(30);
                    page.DefaultTextStyle(x => x.FontSize(9));

                    page.Header().Column(col =>
                    {
                        col.Item().Text(data.ReportTitle)
                            .FontSize(18)
                            .Bold()
                            .FontColor("#06B6D4");
                        col.Item().Text($"Generated: {data.GeneratedAt:yyyy-MM-dd HH:mm} UTC")
                            .FontSize(9)
                            .FontColor("#64748B");
                        col.Item().Text($"Total Rows: {data.TotalRows}")
                            .FontSize(9)
                            .FontColor("#64748B");
                    });

                    page.Content().PaddingVertical(10).Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            foreach (var _ in data.Columns)
                            {
                                columns.RelativeColumn();
                            }
                        });

                        table.Header(header =>
                        {
                            foreach (var col in data.Columns)
                            {
                                header.Cell().Background("#F1F5F9").Padding(4)
                                    .Text(col).Bold().FontColor("#0F172A");
                            }
                        });

                        foreach (var row in data.Rows)
                        {
                            foreach (var cell in row)
                            {
                                table.Cell().Padding(4)
                                    .Text(cell ?? "").FontColor("#334155");
                            }
                        }
                    });

                    page.Footer().AlignCenter()
                        .Text("Generated by Mindora Reporting")
                        .FontSize(9)
                        .FontColor("#94A3B8");
                });
            });

            return document.GeneratePdf();
        }
    }
}