<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mindora.Application\Mindora.Application.csproj" />
    <ProjectReference Include="..\Mindora.Domain\Mindora.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Prompts\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
